#Raúl Melgosa Salvador 70925689Z PB1
memsec:prueba.c Ejercicio1/indice.o Ejercicio2/dispersion.o
	gcc -g prueba.c Ejercicio1/indice.o Ejercicio2/dispersion.o -o memsec
Ejercicio1/indice.o: Ejercicio1/indice.c Ejercicio1/indice.h
	gcc -c -g Ejercicio1/indice.c -o Ejercicio1/indice.o
Ejercicio2/dispersion.o: Ejercicio2/dispersion.c Ejercicio2/dispersion.h
	gcc -c -g Ejercicio2/dispersion.c -o Ejercicio2/dispersion.o
limpiar:
	rm c*
